apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-listeners
  labels: &id001
    app.kubernetes.io/instance: fast-listeners
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  selector:
    matchLabels: *id001
  template:
    metadata:
      labels: *id001
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: fast-listeners
        image: ghcr.io/guilhermelinosp/fast-listeners:v1.2.2
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: fast-listeners
        env:
        - name: HELLNET_SERVICE
          value: fast-listeners
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: fast-database
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fast-database
              key: DATABASE_PASSWORD
        resources:
          requests:
            cpu: 20m
            memory: 48Mi
          limits:
            cpu: '1'
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
