apiVersion: v1
kind: ConfigMap
metadata:
  name: fast-listeners
  namespace: fast
data:
  CACHE_CONNECTION: redis.tools.svc.cluster.local:6379
  CACHE_DEFAULT_TTL: 5m
  CACHE_ENABLE_L2: 'true'
  DATABASE_HOST: postgres.tools.svc.cluster.local
  DATABASE_NAME: fast
  DATABASE_POOL_MAX_SIZE: '10'
  DATABASE_PORT: '5432'
  HELLNET_ENVIRONMENT: Development
  HELLNET_TELEMETRY_ENDPOINT: http://alloy.observability.svc.cluster.local:4318
  KAFKA_BROKERS: redpanda.tools.svc.cluster.local:9093
  KAFKA_DEFAULT_SERIALIZER: avro
  KAFKA_MATCHING_CONSUMER_GROUP: fast-matching
  KAFKA_SCHEMA_REGISTRY_PATH: none
  KAFKA_SCHEMA_REGISTRY_URL: http://redpanda.tools.svc.cluster.local:8081
  KAFKA_SCHEMA_SUBJECT_STRIP_PREFIX: br.com.hellnet.
  KAFKA_SECURITY_PROTOCOL: plaintext
  KAFKA_TOPIC_ORDER_ACCEPTED: br.com.hellnet.fast.order.accepted.v1
  KAFKA_TOPIC_ORDER_REQUESTED: br.com.hellnet.fast.order.requested.v1
